name: preview

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    uses: compliance-framework/workflows/.github/workflows/preview.yml@0820491954d2f748fed5601109a8b6e422deee69 # v1.1.0
    with:
      kind: image
      on-main: true
      images: >-
        [{"name": "mock-agent", "dockerfile": "Dockerfile", "context": "."},
         {"name": "mock-agent-ci", "dockerfile": "Dockerfile-ci", "context": "."},
         {"name": "mock-agent-custodian", "dockerfile": "Dockerfile-custodian", "context": "."}]
    permissions:
      contents: read
      packages: write
