name: release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    uses: compliance-framework/workflows/.github/workflows/release-go-image.yml@main
    with:
      images: >-
        [{"name": "mock-agent", "dockerfile": "Dockerfile", "context": "."},
         {"name": "mock-agent-ci", "dockerfile": "Dockerfile-ci", "context": "."},
         {"name": "mock-agent-custodian", "dockerfile": "Dockerfile-custodian", "context": "."}]
    permissions:
      contents: read
      packages: write
    secrets: inherit
